# Generated by Django 4.2.4 on 2023-11-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0002_alter_university_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemessage',
            name='message',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='clarity_comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='support_comment',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='feedbackdata',
            name='usefulness_comment',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
