# Generated by Django 4.2.4 on 2023-11-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0004_alter_feedback_message_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterModelOptions(
            name='coursemessage',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='feedback',
            options={'verbose_name': 'Feedback', 'verbose_name_plural': 'Feedbacks'},
        ),
        migrations.AlterModelOptions(
            name='feedbackdata',
            options={'verbose_name': 'Feedback data', 'verbose_name_plural': 'Feedback datas'},
        ),
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='tguser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creted date'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated date'),
        ),
    ]
