# Generated by Django 4.2.4 on 2023-11-18 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0005_alter_course_options_alter_coursemessage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='coursemessage',
            options={'verbose_name': 'Course message', 'verbose_name_plural': 'Course messages'},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
    ]
