# Generated by Django 4.2.4 on 2023-12-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0008_alter_coursemessage_language_alter_feedback_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemessage',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('ro', 'ro')], max_length=2),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='language',
            field=models.CharField(choices=[('en', 'en'), ('ro', 'ro')], max_length=2),
        ),
    ]
