from aiogram.fsm.state import StatesGroup, State


class Questions(StatesGroup):
    BEGIN = State()
    LANGUAGE = State()
    UNIVERSITY = State()
    COURSE = State()
    CHOICE = State()
    CHOICE1 = State()
    CHOICE2 = State()
    CHOICE3 = State()
    CHOICE4 = State()
    CHOICE5 = State()
    CHOICE6 = State()
    CHOICE7 = State()
    CHOICE8 = State()
    CHOICE9 = State()
    CHOICE10 = State()
    CHOICE11 = State()
    CHOICE12 = State()
    CHOICE13 = State()
    CHOICE14 = State()
    CHOICE15 = State()
    CHOICE16 = State()
    CHOICE17 = State()
    CHOICE18 = State()
    CHOICE19 = State()
    CHOICE20 = State()
    CHOICE21 = State()
    CHOICE22 = State()
    CHOICE23 = State()
    CHOICE24 = State()
    CHOICE25 = State()
    CHOICE26 = State()
    CHOICE27 = State()
    CHOICE28 = State()
    CHOICE29 = State()
    CHOICE30 = State()
    CLARITY = State()
    CLARITY_FEED = State()
    USEFULNESS = State()
    USEFULNESS_FEED = State()
    SUPPORT = State()
    SUPPORT_FEED = State()
    END = State()    
  